version: '3.8'
services:
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    volumes:
      - ./examples/data:/data
    command: -scheme http -public-host 127.0.0.1:4443
volumes:
  mongodata:
    driver: local
